version: '2'
services:
  prescreeningapplication-app:
    image: prescreeningapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://prescreeningapplication-postgresql:5432/PreScreeningApplication
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 6060:6060
  prescreeningapplication-postgresql:
    extends:
      file: postgresql.yml
      service: prescreeningapplication-postgresql
